#ifndef MG3TR_SRC_CONSTANTS_EPSILONCONSTANT_HPP_INCLUDED
#define MG3TR_SRC_CONSTANTS_EPSILONCONSTANT_HPP_INCLUDED

namespace MG3TR
{
    constexpr float k_epsilon = 0.001F;
}

#endif // MG3TR_SRC_CONSTANTS_EPSILONCONSTANT_HPP_INCLUDED
