#ifndef MG3TR_SRC_CONSTANTS_UTILSCONSTANTS_HPP_INCLUDED
#define MG3TR_SRC_CONSTANTS_UTILSCONSTANTS_HPP_INCLUDED

namespace MG3TR::UtilsConstants
{
    const unsigned k_max_GL_errors_depth_to_print = 10U;
}

#endif // MG3TR_SRC_CONSTANTS_UTILSCONSTANTS_HPP_INCLUDED
