#ifndef MG3TR_SRC_UTILS_STRINGMACROS_HPP_INCLUDED
#define MG3TR_SRC_UTILS_STRINGMACROS_HPP_INCLUDED

#define INTERNAL_STRINGIFY(x) #x
#define STRINGIFY(x) INTERNAL_STRINGIFY(x)

#endif // MG3TR_SRC_UTILS_STRINGMACROS_HPP_INCLUDED
